name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Start Flask app
        run: |
          nohup python main.py > flask.log 2>&1 &  # Start the Flask app in the background
          sleep 10  # Give it time to start

      - name: Display Flask logs
        run: cat flask.log  # Useful for debugging if the server fails to start

      - name: Run API tests
        run: pytest tests/test_code.py  # Run API tests

      - name: Stop Flask app
        run: pkill -f main.py || true  # Ensure the Flask app is stopped after tests
